version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: intellihome_user
      POSTGRES_PASSWORD: intellihome_password
      POSTGRES_DB: intellihome_sql
    ports:
      - "5432:5432"
    working_dir: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tty: true

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    working_dir: /var/lib/influxdb
    volumes:
      - influxdb_data:/etc/influxdb/influxdb
    tty: true

  # react_frontend:
  #   image: node:alpine
  #   container_name: react_frontend
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   working_dir: /srv/app
  #   volumes:
  #     - type: bind
  #       source: ./IntelliHome-Frontend
  #       target: /srv/app
  #   tty: true
  #   command: sh -c "npm install && npm run dev"

  # dotnet_backend:
  #   image: mcr.microsoft.com/dotnet/sdk:6.0
  #   container_name: dotnet_backend
  #   restart: always
  #   ports:
  #     - 5283:5283
  #   working_dir: /app
  #   volumes:
  #     - type: bind
  #       source: ./IntelliHome-Backend/IntelliHome-Backend
  #       target: /app
  #   tty: true
  #   command: sh -c "./wait-for-postgres.sh"
  #   depends_on:
  #     - postgres



volumes:
  postgres_data:
  influxdb_data:

